### ISSUE TITLE
Item NPC gives you sometimes randomly dissappears

### ISSUE THREAD

**Issue by joshiejack** [joshiejack/Harvest-Moon#116] opened 2016-12-12 17:27 UTC
I've been unable to trace the cause. Or recreate it.

If you've had this happen, please leave comment how/when and under what conditions, held items, things clicked and if you consistently have the issue.

**Comment by Divineaspect** [comment] 2016-12-12 18:23
When I have it happen it's a desync, I only have had it on a server.

**Comment by Peach774** [comment] 2016-12-12 20:23
It happens in singleplayer as well. But it is very similar to a desync. I think it has something to do with how the mod checks the players inventory and when it does it.

**Comment by piemantr** [comment] 2016-12-14 02:17
I play on Singleplayer. When I turn in the 9 Hardy Turnips to Jade, the reward was a Sickle and seeds. They appear in my inventory after my conversation with Jade but once I open my inventory or a chest, they disappear.

**Comment by joshiejack** [comment] 2016-12-14 06:24
Hmm, I've tried to recreate that one you say piemantr like 30 odd times at least, every time I've had no issue :(. Ya'll must be doing something else differently.

**Comment by LameGirlyCurly** [comment] 2016-12-16 08:09
We're having the same issue with both our server (running sponge) and singleplayer. Using latest version of the mod and the pack is FarmingValley. Both sickels and hoes traded with the npc disappear after few steps away.

**Comment by Zarvoxbe** [comment] 2017-01-09 12:10
I've the same problem but I think I've found the cause of the problem.

In the modpack I'm playing I've Inventory Tweack/Mouse Tweack, i've disabled both and no more item dissappearing.

I think IT is the main cause because once I re-enable it the problem return.

**Comment by Dfox444** [comment] 2017-02-07 18:33
I had this issue happen to the miner, i talked to him and he tried to give me copper ore but it replaced my iron sword in slot 1, i opened my inventory, tried to drag it and it turned back to the sword and the copper ore was gone. This has happened with pretty much every npc so far up to the miner. This was done on a server with another person so it could be a multiplayer issue. It was also in the Farming Valley modpack.

**Comment by Dfox444** [comment] 2017-02-08 23:47
It seems having an open hotbar gives you everything without replacing or deleting items.

**Comment by jamzam90** [comment] 2017-04-02 06:23
Ive had it happen in singleplayer, I think it's not checking if a slot is empty in the inventory prior to giving the item.

**Comment by joshiejack** [comment] 2017-04-24 07:57
I rewrote parts of the quest system in 0.6. Ideally anyone who can test if this still occurs will be apreciated.

**Comment by KMFrench1** [comment] 2017-07-13 21:25
This is happening on a server I play with my friends. there are just 3 of us. but every time we give a tool to the blacksmith (for upgrade or repair) when he gives it back it appears on hot bar, the disappears as soon as we open our inventory. this happens to all 3 of us. Any idea the cause?

**Comment by bizleycraft** [comment] 2017-07-14 18:45
'This is happening on a server I play with my friends. there are just 3 of us.'

I had exactly the same problem until a minute ago, using the latest version of Harvest Festival with 0.5.27 in the current version of Farming Valley (which doesn't have inventory tweaks). It was really ruining my enjoyment for the half hour before I found this thread.

'I rewrote parts of the quest system in 0.6. Ideally anyone who can test if this still occurs will be apreciated.'

Tested on 0.6.0-218 on my dedicated server, and... fixed!

**Comment by hugojmaia** [comment] 2017-11-20 14:53
I can confirm this bug.
It'll happen nearly every time something is on the first slot of the hotbar, only workaround is to re-train on organizing it.
Playing on the 5.27 version.

**Comment by Klaabu5** [comment] 2017-12-12 16:44
Happens with empty hotbar also.
MC:1.10.2
Forge:*.2511
Harvest Festival:0.5.27
Modpack: Farming Valley 0.9.1

**Comment by GirafiStudios** [comment] 2017-12-19 05:44
Should be fixed in 0.6. Please open a new issue, if you are able to reproduce it for 0.6 though!

**Closed as completed by GirafiStudios** 2017-12-19 05:44 UTC

**Comment by Concolora** [comment] 2018-03-10 02:49
So, this just happened to me in singleplayer (though opened to LAN with one other player).  The upgraded tool appeared in the first slot of my hotbar (replacing a diamond pick) and also the first empty slot of the hotbar.  When I tried to move the upgraded tool (copper watering can), both vanished and the pick reappeared.

MC:1.10.2
Forge: .2511
Harvest Festival: 0.5.27
Modpack: Farming Valley 0.9.1

**Comment by GirafiStudios** [comment] 2018-03-10 03:15
As stated previously, in this issue even, this is fixed in 0.6+

**Comment by JevilFromVSauce** [comment] 2020-10-12 13:33
Still having the Issue Concolora mentioned and I'm in 0.9

**Comment by hunter-goller** [comment] 2021-08-11 22:08
This just happened to me on my friends and my multiplayer world the blacksmith to upgrade/ repair anything takes the items and gold but never gives the item back it just dissappears.
