### ISSUE TITLE
Crash with BlockDrops

### ISSUE THREAD

**Issue by rigerc** [joshiejack/Harvest-Moon#22] opened 2016-09-24 00:41 UTC
Experiencing a crash on load with BlockDrops installed (mod which analyzes what blocks drop) on Forge 2089.

Here's the crash log it spits out
https://gist.github.com/bondgb/017ffe630d96486f49a28c2afab60411

**Comment by GirafiStudios** [comment] 2016-09-24 00:44
Thanks for your report!
Harvest Festival is not even mentioned in that crash log ? :)
Looks like it is Giacomos Foundry, whatever that is.

**Comment by rigerc** [comment] 2016-09-24 00:58
Oh, that's weird. Boots up fine without Harvest Festival. I'll see if I can make a issue report with Giacomo's then. That mod hasn't been updated in a while though.

https://minecraft.curseforge.com/projects/giacomos-foundry?gameCategorySlug=mc-mods&projectID=231254

**Comment by GirafiStudios** [comment] 2016-09-24 01:05
Sorry about my comment before, it wasen't true that Harvest Festival wasen't mentioned at all. I guess my tired brain just missed it :)
I tried to reproduce this with just JEI, Block Drops, Harvest Festival and Gyacomo's Foundry and I couldn't reproduce it.

**Comment by GirafiStudios** [comment] 2016-09-24 01:17
@bondgb could you try updating all your mods (And Forge) to the latest version and see if this still happen? :)

**Comment by rigerc** [comment] 2016-09-24 01:23
All my mods are updated, but I'll update forge tomorrow and check.

**Comment by rigerc** [comment] 2016-09-24 06:26
Updating Forge doesn't seem to help. I'll try and narrow it down some more tonight, but dunno. Would a mod that makes changes to vanilla mobs affect HF?

**Comment by GirafiStudios** [comment] 2016-09-24 06:30
I doubt it.
Joshiejack might have fixed it earlier, but since I can't reproduce it you will have to wait until next release to test if it is fixed :)
Will happen later today at some point most likely.

**Comment by GirafiStudios** [comment] 2016-09-24 06:54
Harvest Festival 0.5.2 is now up on CurseForge: https://minecraft.curseforge.com/projects/harvest-festival/files/2332052
Could you please try that, and see if it fixes your issue ? :)

**Comment by rigerc** [comment] 2016-09-24 16:32
Still no luck, the error changed though, it's now 
java.lang.IndexOutOfBoundsException: Index: 21, Size: 21 but don't think that tells you anything.

**Comment by GirafiStudios** [comment] 2016-09-24 16:35
Still crashing on startup?
Also could you give me that crash report, looks like it have changed a bit :)

**Comment by rigerc** [comment] 2016-09-24 16:39
Yep, still on startup. Here's the most recent log: https://gist.github.com/bondgb/795ef43b6c73db650dff3a415afcb95f

Here's my fml-client-latest.log: https://gist.github.com/bondgb/507d3da643fca867619c14991a0a68fb

 I can't really see anything noteworthy in there, Block Drops spits out some errors on analyzed blocks but that's not uncommon for a lot of mods.

**Comment by GirafiStudios** [comment] 2016-09-24 16:42
Sure, why not :)
Also could you try to remove Giacomo's Foundry, just to check if it crashes without that?

Edit: You don't have to, joshie messed up! Hopefully it will be fixed in next version :p

**Comment by joshiejack** [comment] 2016-09-24 16:48
Woops, my maths brain broke

**Comment by GirafiStudios** [comment] 2016-09-24 19:49
@bondgb could you try out the latest Jenkins build from here: http://joshiejack.uk:8080/job/Harvest-Festival/job/1.10.2/81/ ? :) It should be fixed there!

**Comment by rigerc** [comment] 2016-09-24 20:01
Confirmed, starts up fine! Thanks

**Comment by GirafiStudios** [comment] 2016-09-24 20:06
Great!
Thank you for helping testing out different builds of Harvest Festival, saved us some work :)

**Closed as completed by GirafiStudios** 2016-09-24 20:06 UTC
Labels: bug, to investigate
