### ISSUE TITLE
Blueprints disapeared from Carpenters Shop

### ISSUE THREAD

**Issue by Remyrios** [joshiejack/Harvest-Moon#125] opened 2017-01-15 14:42 UTC
Thank you for reporting!
---

I'm using Forge 12.18.3.2185 and latest version of Harvest Festival. I don't know when exactly it happened but i know that happened after i slept. All Blueprints that was avialable just disapeared. Is it a bug or it's intentional?

**Comment by joshiejack** [comment] 2017-01-15 15:30
No clue how that would happen. And not had it happen to me. If you can find a way to recreate it, then I'd be able to investigate the root cause.

**Comment by Remyrios** [comment] 2017-01-15 18:40
I'm using Modpack Farming Valley so that can be a thing. And as far as i rememmber this day i also didn't get money from shipping bay.
(Yeah there were plants inside)

**Comment by joshiejack** [comment] 2017-04-22 07:17
Hopefully fixed in 0.6 so closing

**Closed as completed by joshiejack** 2017-04-22 07:17 UTC
