### ISSUE TITLE
Watering can turning back to bucket

### ISSUE THREAD

**Issue by Jester0914** [joshiejack/Harvest-Moon#107] opened 2016-11-18 10:06 UTC
I'm trying to replace my watering can because i died in Lava, but when i bring a bucket to the carpenters daughter, she gives me a watering can. However, when you fill it or drop it, it turns into a bucket.

**Comment by joshiejack** [comment] 2016-12-10 23:42
This is an ongoing issue and doesn't appear consistent and seems to happen randomly. Until someone can give me exact instructions that can help recreate this sort of issue then I'm unable to fix it. I've been unable to recreate it at all so far. And I need to be able to in order to investigate what is causing the issue.

**Comment by Jester0914** [comment] 2016-12-10 23:45
What happened to me, was after I got the carpenter moved in, I ended up
dropping my watering can for my friend then I took the bucket to the girl
got a watering can, then upon equipping or moving it, it returned to being
a bucket.

**Comment by Jester0914** [comment] 2016-12-10 23:47
Also the whole death thing happened too

**Comment by joshiejack** [comment] 2016-12-10 23:49
I know what happens. But every time I've done the same thing. It has not happened for me.

**Comment by Jester0914** [comment] 2016-12-10 23:52
Hmm, I'll see if i can recreat and record it, would that help?

**Comment by joshiejack** [comment] 2016-12-11 08:59
Not really. I need some exact instructions that will always cause it, or cause it to happen frequently. I mean, earlier I tested and I repaired/upgraded things fine like 50 times, tried in fev, on a pack and on smp. Before ive tried it with other quests and I think it happened once but since I can't recreate easily, I can't debug it, I have no wild guesses either atm xD.

There has to be some sequence of events that cause it to fail but so far everyones had a different story, so hard to pin down. I think I can understand what must be happening when it messes up, but looking at the code, can't work out how it messes up xD. Like it must be that reward ares only getting given clientside but, I'm literally sending a packet after they're claimed on the server >.>.  So i'm lost tbh xD

**Comment by Jester0914** [comment] 2016-12-11 15:07
Haha, I gotcha, I will try and find a way to constantly recreate it
later.I'm sorry this one eludes you as far as answers, I will do what I can
to help!

**Comment by P3rf3ctXZer0** [comment] 2016-12-11 21:27
@Jester0914 Can I have a copy of your mod-pack and instructions on how its being caused?

**Comment by Jester0914** [comment] 2016-12-15 05:46
Yes you can I'm just kinda busy these couple days

**Comment by CJBok** [comment] 2016-12-29 20:28
I think this issue might be caused by inventory tweaks.... Which can make the client and server being out of sync when it comes to item positions in players inventory.

**Comment by Jester0914** [comment] 2017-01-04 06:12
Sounds plausible.

**Comment by joshiejack** [comment] 2017-01-15 12:59
Going to close this as the route cause is the same as #116

**Closed as completed by joshiejack** 2017-01-15 12:59 UTC
