### ISSUE TITLE
Harvest Festival's Food Trough and RFPR crash

### ISSUE THREAD

**Issue by DcNdrew** [joshiejack/Harvest-Moon#122] opened 2016-12-30 15:01 UTC
I'm using Realistic First-Person Renderer 8.1.1, which is the last version.
When I'm trying to take in my hand the Food Trough, the game crashes.
The log refers to the RFPR, so it may not your problem, but if you know what's the difference between the trough and your other items, you'll may know what caused this.

http://paste.ee/p/nudtE

I had no problems any other items, and without RFPR it works right.

**Comment by joshiejack** [comment] 2016-12-30 15:03
Duplicate of https://github.com/PenguinSquad/Harvest-Festival/issues/110

Not my mod crashing

**Closed as completed by joshiejack** 2016-12-30 15:03 UTC

**Comment by DcNdrew** [comment] 2016-12-30 15:06
Sorry. :D
