### ISSUE TITLE
crash when opening township inventory in creative mode

### ISSUE THREAD

**Issue by scigeotech** [joshiejack/Harvest-Moon#19] opened 2016-09-23 20:03 UTC
here's the crash report;

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  RenderPlayerAPIPlugin (RenderPlayerAPI-1.10.2-1.1.jar)
  HFTransformer (Harvest-Festival-1.10.2-0.5.0.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 9/23/16 4:00 PM
Description: Rendering Block Entity

java.lang.ClassCastException: joshie.harvest.npc.entity.EntityNPCVillager cannot be cast to net.minecraft.entity.player.EntityPlayer
    at com.mrcrayfish.skateboarding.client.model.ModelPlayerOverride.render(ModelPlayerOverride.java:120)
    at api.player.model.ModelPlayerAPI.render(Unknown Source)
    at api.player.model.ModelPlayerAPI.render(Unknown Source)
    at net.minecraft.client.model.ModelPlayer.func_78088_a(SourceFile)
    at joshie.harvest.npc.render.NPCItemRenderer.renderTileEntityAt(NPCItemRenderer.java:44)
    at joshie.harvest.npc.render.NPCItemRenderer.func_180535_a(NPCItemRenderer.java:16)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(TileEntityRendererDispatcher.java:131)
    at joshie.harvest.asm.RenderHook.render(RenderHook.java:32)
    at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.func_179022_a(TileEntityItemStackRenderer.java)
    at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:146)
    at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:309)
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:348)
    at mezz.jei.gui.ingredients.GuiItemStackFast.renderSlow(GuiItemStackFast.java:148)
    at mezz.jei.gui.ingredients.GuiItemStackFastList.render(GuiItemStackFastList.java:148)
    at mezz.jei.gui.ItemListOverlay.drawScreen(ItemListOverlay.java:329)
    at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:86)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_70_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at com.mrcrayfish.skateboarding.client.model.ModelPlayerOverride.render(ModelPlayerOverride.java:120)
    at api.player.model.ModelPlayerAPI.render(Unknown Source)
    at api.player.model.ModelPlayerAPI.render(Unknown Source)
    at net.minecraft.client.model.ModelPlayer.func_78088_a(SourceFile)
    at joshie.harvest.npc.render.NPCItemRenderer.renderTileEntityAt(NPCItemRenderer.java:44)
    at joshie.harvest.npc.render.NPCItemRenderer.func_180535_a(NPCItemRenderer.java:16)

-- Block Entity Details --
Details:
    Name: null // joshie.harvest.npc.render.NPCItemRenderer.NPCTile
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(TileEntityRendererDispatcher.java:131)
    at joshie.harvest.asm.RenderHook.render(RenderHook.java:32)
    at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.func_179022_a(TileEntityItemStackRenderer.java)
    at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:146)
    at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:309)

-- Item being rendered --
Details:
    Item Type: joshie.harvest.npc.item.ItemNPCSpawner@4ba047
    Item Aux: 12
    Item NBT: null
    Item Foil: false
Stacktrace:
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:348)
    at mezz.jei.gui.ingredients.GuiItemStackFast.renderSlow(GuiItemStackFast.java:148)
    at mezz.jei.gui.ingredients.GuiItemStackFastList.render(GuiItemStackFastList.java:148)
    at mezz.jei.gui.ItemListOverlay.drawScreen(ItemListOverlay.java:329)
    at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:86)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_70_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (446, 15). Absolute: (893, 674)
    Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['ItSureStingz'/276, l='MpServer', x=-13.55, y=79.00, z=97.64]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-28,64,92), Chunk: (at 4,4,12 in -2,5; contains blocks -32,0,80 to -17,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 53537 game time, 25595 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 111 total; [EntityCreeper['Creeper'/1797, l='MpServer', x=-52.50, y=14.00, z=156.50], EntitySkeleton['Skeleton'/2070, l='MpServer', x=17.30, y=33.00, z=154.44], EntitySkeleton['Skeleton'/2071, l='MpServer', x=18.50, y=33.00, z=156.50], EntityCreeper['Creeper'/1817, l='MpServer', x=-72.50, y=42.00, z=173.50], EntityCreeper['Creeper'/2330, l='MpServer', x=-20.50, y=47.00, z=52.50], EntityCreeper['Creeper'/1818, l='MpServer', x=-75.50, y=42.00, z=177.50], EntityCreeper['Creeper'/1819, l='MpServer', x=-76.50, y=42.00, z=177.50], EntityZombie['Zombie'/2335, l='MpServer', x=-1.50, y=8.00, z=74.50], EntityPlayerSP['ItSureStingz'/276, l='MpServer', x=-13.55, y=79.00, z=97.64], EntityCreeper['Creeper'/1587, l='MpServer', x=-22.50, y=41.00, z=86.50], EntitySkeleton['Skeleton'/2359, l='MpServer', x=-93.50, y=34.00, z=155.50], EntitySkeleton['Skeleton'/1606, l='MpServer', x=-25.53, y=50.00, z=50.28], EntitySkeleton['Skeleton'/2377, l='MpServer', x=-69.50, y=27.00, z=174.50], EntitySkeleton['Skeleton'/2378, l='MpServer', x=-70.50, y=27.00, z=174.50], EntitySkeleton['Skeleton'/2379, l='MpServer', x=-68.50, y=29.00, z=164.79], EntitySquid['Squid'/2124, l='MpServer', x=-20.45, y=51.00, z=119.40], EntitySkeleton['Skeleton'/2380, l='MpServer', x=-71.50, y=27.00, z=172.50], EntitySquid['Squid'/2125, l='MpServer', x=-23.54, y=52.14, z=122.77], EntitySquid['Squid'/2126, l='MpServer', x=-30.15, y=53.35, z=131.20], EntitySkeleton['Skeleton'/1615, l='MpServer', x=-11.50, y=26.00, z=87.50], EntitySquid['Squid'/2127, l='MpServer', x=-24.32, y=51.00, z=129.55], EntitySquid['Squid'/2128, l='MpServer', x=-41.26, y=52.19, z=112.43], EntitySquid['Squid'/2129, l='MpServer', x=-47.14, y=51.08, z=119.18], EntitySquid['Squid'/2130, l='MpServer', x=-42.07, y=52.11, z=112.40], EntitySquid['Squid'/2131, l='MpServer', x=-43.72, y=51.68, z=113.51], EntitySquid['Squid'/2132, l='MpServer', x=-35.70, y=58.76, z=150.29], EntitySquid['Squid'/2133, l='MpServer', x=-51.40, y=62.56, z=145.53], EntitySquid['Squid'/2134, l='MpServer', x=-51.57, y=60.33, z=153.51], EntitySquid['Squid'/2135, l='MpServer', x=-46.69, y=62.45, z=151.26], EntitySquid['Squid'/2142, l='MpServer', x=37.40, y=47.00, z=123.40], EntityItem['item.item.feather'/1887, l='MpServer', x=-65.79, y=64.00, z=87.21], EntitySquid['Squid'/2143, l='MpServer', x=27.77, y=58.75, z=149.09], EntityItem['item.item.chickenRaw'/1888, l='MpServer', x=-67.05, y=64.00, z=86.45], EntitySquid['Squid'/2144, l='MpServer', x=20.58, y=56.45, z=150.56], EntitySquid['Squid'/2145, l='MpServer', x=30.10, y=56.12, z=158.74], EntitySquid['Squid'/2146, l='MpServer', x=23.38, y=56.06, z=155.48], EntityCreeper['Creeper'/2405, l='MpServer', x=55.50, y=37.00, z=85.50], EntityCreeper['Creeper'/2406, l='MpServer', x=55.50, y=37.00, z=84.50], EntityBat['Bat'/2411, l='MpServer', x=-12.01, y=15.26, z=129.39], EntityBat['Bat'/2419, l='MpServer', x=-89.60, y=29.64, z=133.30], EntityBat['Bat'/2420, l='MpServer', x=-92.23, y=29.89, z=131.71], EntitySkeleton['Skeleton'/1675, l='MpServer', x=-78.50, y=15.00, z=140.50], EntitySquid['Squid'/2198, l='MpServer', x=4.80, y=51.44, z=160.05], EntitySquid['Squid'/2199, l='MpServer', x=9.03, y=51.54, z=159.76], EntityBat['Bat'/2459, l='MpServer', x=14.49, y=24.03, z=70.25], EntitySquid['Squid'/2206, l='MpServer', x=-17.20, y=54.18, z=133.30], EntitySquid['Squid'/2207, l='MpServer', x=-7.68, y=55.92, z=132.23], EntitySquid['Squid'/2208, l='MpServer', x=-10.32, y=53.30, z=133.58], EntitySquid['Squid'/2209, l='MpServer', x=-10.35, y=53.81, z=134.82], EntityHorse['Horse'/162, l='MpServer', x=-75.00, y=67.00, z=35.08], EntityItem['item.tile.torch'/163, l='MpServer', x=-73.91, y=58.00, z=67.13], EntityItem['item.tile.sand.default'/164, l='MpServer', x=-71.70, y=62.00, z=94.87], EntityItem['item.tile.sandStone.default'/165, l='MpServer', x=-72.83, y=60.00, z=93.68], EntityItem['item.tile.sand.default'/166, l='MpServer', x=-70.20, y=61.00, z=93.76], EntityItem['item.tile.sand.default'/167, l='MpServer', x=-74.45, y=62.00, z=93.41], EntityItem['item.tile.sandStone.default'/168, l='MpServer', x=-73.13, y=60.00, z=91.53], EntityItem['item.tile.sand.default'/169, l='MpServer', x=-71.29, y=60.00, z=93.81], EntityItem['item.tile.sand.default'/170, l='MpServer', x=-70.64, y=62.00, z=93.95], EntityItem['item.tile.sandStone.default'/171, l='MpServer', x=-71.13, y=60.00, z=91.88], EntityItem['item.tile.sand.default'/172, l='MpServer', x=-74.41, y=60.00, z=91.98], EntityItem['item.tile.sand.default'/173, l='MpServer', x=-73.54, y=60.00, z=92.34], EntityItem['item.tile.sand.default'/174, l='MpServer', x=-72.34, y=61.00, z=92.41], EntityItem['item.tile.sandStone.default'/175, l='MpServer', x=-74.88, y=60.00, z=91.48], EntityItem['item.tile.sandStone.default'/176, l='MpServer', x=-73.43, y=60.00, z=90.13], EntityItem['item.tile.sand.default'/177, l='MpServer', x=-75.23, y=62.00, z=91.13], EntityItem['item.tile.sand.default'/178, l='MpServer', x=-70.97, y=60.00, z=90.41], EntityItem['item.tile.sand.default'/179, l='MpServer', x=-72.18, y=60.00, z=90.52], EntityItem['item.tile.sand.default'/180, l='MpServer', x=-70.13, y=60.00, z=90.35], EntityItem['item.tile.sand.default'/181, l='MpServer', x=-73.89, y=60.00, z=90.58], EntityItem['item.tile.sand.default'/182, l='MpServer', x=-71.51, y=60.00, z=89.13], EntityItem['item.tile.sand.default'/183, l='MpServer', x=-73.13, y=61.00, z=89.06], EntityItem['item.tile.sand.default'/184, l='MpServer', x=-73.19, y=60.00, z=93.83], EntityItem['item.tile.sand.default'/185, l='MpServer', x=-75.88, y=62.00, z=92.00], EntityItem['item.item.feather'/1977, l='MpServer', x=-71.40, y=60.00, z=93.88], EntityItem['item.tile.sand.default'/186, l='MpServer', x=-72.35, y=61.00, z=93.96], EntityItem['item.item.chickenRaw'/1978, l='MpServer', x=-71.60, y=60.00, z=93.88], EntityItem['item.tile.sand.default'/187, l='MpServer', x=-73.29, y=60.00, z=91.47], EntityItem['item.item.bone'/1979, l='MpServer', x=-71.80, y=60.00, z=93.88], EntityBat['Bat'/2491, l='MpServer', x=39.38, y=33.99, z=95.55], EntityTameableDragon['Ender Dragon'/188, l='MpServer', x=-70.95, y=64.00, z=83.00], EntityItem['item.tile.sand.default'/189, l='MpServer', x=-75.04, y=64.00, z=94.41], EntityHorse['Horse'/191, l='MpServer', x=-63.96, y=67.00, z=34.12], EntityItem['item.tile.torch'/194, l='MpServer', x=-51.13, y=48.00, z=111.55], EntitySkeleton['Skeleton'/1730, l='MpServer', x=-53.50, y=15.00, z=157.50], EntityHorse['Horse'/197, l='MpServer', x=-38.00, y=64.00, z=51.10], EntityBat['Bat'/2245, l='MpServer', x=32.26, y=21.22, z=75.36], EntityBat['Bat'/1992, l='MpServer', x=-3.16, y=27.76, z=115.48], EntityCow['Cow'/203, l='MpServer', x=58.81, y=63.09, z=31.46], EntityCow['Cow'/204, l='MpServer', x=60.38, y=63.00, z=29.18], EntityBat['Bat'/2509, l='MpServer', x=-75.90, y=29.28, z=166.35], EntityCow['Cow'/205, l='MpServer', x=65.40, y=62.71, z=22.39], EntityCow['Cow'/206, l='MpServer', x=56.41, y=65.00, z=22.15], EntitySkeleton['Skeleton'/1743, l='MpServer', x=-17.15, y=13.00, z=145.70], EntityCow['Cow'/207, l='MpServer', x=50.80, y=66.00, z=23.54], EntityZombie['entity.Zombie.name'/1744, l='MpServer', x=-17.85, y=13.00, z=144.99], EntityCow['Cow'/208, l='MpServer', x=56.33, y=62.26, z=34.14], EntityCow['Cow'/209, l='MpServer', x=51.77, y=63.09, z=75.49], EntityCow['Cow'/210, l='MpServer', x=55.51, y=64.00, z=71.45], EntityCow['Cow'/211, l='MpServer', x=65.50, y=64.00, z=30.50], EntityBat['Bat'/2006, l='MpServer', x=-65.80, y=12.85, z=147.25], EntityPig['Pig'/214, l='MpServer', x=63.23, y=62.27, z=54.82], EntitySpider['Spider'/2519, l='MpServer', x=41.50, y=31.00, z=92.50], EntityPig['Pig'/216, l='MpServer', x=61.67, y=65.00, z=75.50], EntityPig['Pig'/217, l='MpServer', x=66.01, y=64.00, z=70.15], EntityCreeper['Creeper'/2022, l='MpServer', x=-74.50, y=13.00, z=139.50], EntityCreeper['Creeper'/2023, l='MpServer', x=-73.50, y=13.00, z=140.50], EntityCreeper['Creeper'/2024, l='MpServer', x=-69.50, y=13.00, z=138.50], EntityZombie['Zombie'/2025, l='MpServer', x=-72.50, y=13.00, z=140.50], EntityCreeper['Creeper'/2552, l='MpServer', x=-11.50, y=40.00, z=82.50], EntityCreeper['Creeper'/2553, l='MpServer', x=-7.16, y=40.00, z=85.50], EntityCreeper['Creeper'/2554, l='MpServer', x=-7.92, y=40.00, z=85.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (x86) version 10.0
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 173036704 bytes (165 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.1.2092 21 mods loaded, 21 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2092.jar) 
    UCHIJAAAA   Forge{12.18.1.2092} [Minecraft Forge](forge-1.10.2-12.18.1.2092.jar) 
    UCHIJAAAA   RenderPlayerAPI{1.1} [Render Player API](minecraft.jar) 
    UCHIJAAAA   JEI{3.10.0.261} [Just Enough Items](jei_1.10.2-3.10.0.261.jar) 
    UCHIJAAAA   appleskin{1.0.4} [AppleSkin](AppleSkin-mc1.10.2-1.0.4.jar) 
    UCHIJAAAA   cannibalism{3.0.0} [Cannibalism](Cannibalism-3.0.0-1.10.2.jar) 
    UCHIJAAAA   claycraft{3.0} [Claycraft](Claycraftmod v3.0 - MC1.10.2 Forge.jar) 
    UCHIJAAAA   cordage{1.0.1} [Cordage](cordage-1.0.1.jar) 
    UCHIJAAAA   csm{1.0} [MrCrayfish's Skateboarding Mod](csm-1.0-alpha2-mc1.9.4.jar) 
    UCHIJAAAA   simpleArtilleryMod{Alpha1_0_2} [CustomizableArtilleryMod](CustomizableArtilleryMODv1_0_2forMC1.10.2.jar) 
    UCHIJAAAA   DragonMounts{r46-1.10.2} [Dragon Mounts](DragonMounts-r46-1.10.2.jar) 
    UCHIJAAAA   lootablebodies{2.2.0} [DrCyano's Lootable Bodies](DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
    UCHIJAAAA   F2L{1.10.2} [Flesh2Leather](Flesh2Leather [1.10.2].jar) 
    UCHIJAAAA   samsfooddetails{1.0.1} [Food Details](FoodDetails-1.10.2-1.0.1.jar) 
    UCHIJAAAA   foragecraft{1.7} [ForageCraft](ForageCraft-1.7.jar) 
    UCHIJAAAA   fishing{1.4.4} [Fishing Net Mod](GiacomosFishingNet1.10.2-1.4.4.jar) 
    UCHIJAAAA   harvestfestival{0.5.0} [Harvest Festival](Harvest-Festival-1.10.2-0.5.0.jar) 
    UCHIJAAAA   Neat{1.3-12} [Neat](Neat 1.3-12.jar) 
    UCHIJAAAA   pplus{1.10.2} [Peaceful Plus](Peaceful Plus [1.10.2].jar) 
    UCHIJAAAA   shellMod{Beta1_5_1} [shellMod](ShellsMod1_5_1forMC1.10.2.jar) 
    Loaded coremods (and transformers): 
RenderPlayerAPIPlugin (RenderPlayerAPI-1.10.2-1.1.jar)
  api.player.forge.RenderPlayerAPITransformer
HFTransformer (Harvest-Festival-1.10.2-0.5.0.jar)
  joshie.harvest.asm.HFTransformer
    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4400'
    Launched Version: 1.10.2-forge1.10.2-12.18.1.2092
    LWJGL: 2.9.4
    OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4331, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz
```

**Comment by GirafiStudios** [comment] 2016-09-23 20:14
Thanks for the report!
The crash is caused by MrCrayfish's Skateboarding Mod, and is actually caused by some unused code here: https://github.com/MrCrayfish/MrCrayfishSkateboardingMod/blob/master/src/main/java/com/mrcrayfish/skateboarding/client/model/ModelPlayerOverride.java#L120

**Comment by GirafiStudios** [comment] 2016-09-23 20:35
I have opened a pull request with a proposed fix for this crash here: https://github.com/MrCrayfish/MrCrayfishSkateboardingMod/pull/3, unfornuately we can't really do anything on our side to fix it. So you would have to remove MrCrayfish's Skateboarding Mod until the pull request is accepted :)

**Closed as completed by GirafiStudios** 2016-09-23 20:35 UTC
