### ISSUE TITLE
Snow after winter

### ISSUE THREAD

**Issue by BionicFelps** [joshiejack/Harvest-Moon#66] opened 2016-10-07 08:00 UTC
Due to the way minecraft physics works, snow doesn't melt unless there's a nearby torch, any plans to alter this behavior in warmer seasons? Minor immersion nitpick, spose it's not really a bug, just the way minecraft works...

**Comment by GirafiStudios** [comment] 2016-10-07 09:12
Thanks for reporting!
This is a duplicate of https://github.com/PenguinSquad/Harvest-Festival/issues/64, another time please check closed reports to see if your issue have already been reported! :)

**Closed as completed by GirafiStudios** 2016-10-07 09:12 UTC
