### ISSUE TITLE
Freeze and hangup attempting to open NPC store

### ISSUE THREAD

**Issue by Andvee** [joshiejack/Harvest-Moon#189] opened 2017-11-10 06:47 UTC
forge - 12.18.3.2316
HF - 0.6.0-218

latest.log:
https://gist.github.com/Andvee/d66d8890f18aadf7ca3923b0820ca45e

Game will hangup and freeze when trying to talk to Jim and open his store.

Other mods removed prior to the error including BOP, baby mobs, waddles, morpheus, hwyla, wawla, and tough as nails. Seem to be the change that precipitated the error.

**Comment by Andvee** [comment] 2017-11-10 12:47
narrowed the issue down. Recreated problem by removing only tough as nails. Problem resolves when tough as nails is re-added.

**Comment by GirafiStudios** [comment] 2017-11-10 13:28
Thanks for the report!
So are you saying that the issue is only there with or without Tough as Nails?

**Comment by Andvee** [comment] 2017-11-10 23:20
There was no issue until tough as nails was removed. When Tough as Nails is present it interferes with HF's snow and seasons... attempting to remove it causes this issue.

**Comment by GirafiStudios** [comment] 2017-11-11 01:47
Fixed by https://github.com/PenguinSquad/Harvest-Festival/commit/807e4436050112f184559afd65bf3e687892f6cc

**Closed as completed by GirafiStudios** 2017-11-11 01:47 UTC
